services:
  web:
    image: ${DOCKERHUB_USER:-local}/utrack-frontend:${APP_RELEASE:-latest}
    build:
      context: .
      dockerfile: ./web/Dockerfile.web

  space:
    image: ${DOCKERHUB_USER:-local}/utrack-space:${APP_RELEASE:-latest}
    build:
      context: ./
      dockerfile: ./space/Dockerfile.space

  admin:
    image: ${DOCKERHUB_USER:-local}/utrack-admin:${APP_RELEASE:-latest}
    build:
      context: ./
      dockerfile: ./admin/Dockerfile.admin

  api:
    image: ${DOCKERHUB_USER:-local}/utrack-backend:${APP_RELEASE:-latest}
    build:
      context: ./apiserver
      dockerfile: ./Dockerfile.api

  proxy:
    image: ${DOCKERHUB_USER:-local}/utrack-proxy:${APP_RELEASE:-latest}
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
